server:
  port: 8080

spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        id:
          new_generator_mappings: true
        format_sql: true
        use_sql_comments: true
        show_sql: false
        hbm2ddl:
          auto: update
    defer-datasource-initialization: true